apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx:
    container.seccomp.security.alpha.kubernetes.io/pod:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      automountServiceAccountToken: false
      serviceAccountName: dso-demo
      containers:
      - image: jerry871002/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
          runAsGroup: 11000
status: {}
